main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('create-post', views.create_post, name='create_post'),
    path('mypost', views.my_post, name='my_post'),
    path('editpost/<int:id>/', views.create_post, name='edit_post'),
    path('updatepost/<int:id>/', views.update_post, name='update_post'),

    path('mycart/', views.my_cart, name='my_cart'),
    path('myorder/', views.my_order, name='my_order'),

    

]

virtuallearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)
    description = models.TextField()
    amount = models.DecimalField(max_digits=7, decimal_places=2, default=99, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + "\n" + self.description


class Cart(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=99, null=False, blank=False)

    def __str__(self):
        return self.author.username+"@@"+self.post.title
    
class Order(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=99, null=False, blank=False)
    address = models.CharField (max_length=50, default='', blank=True)
    phone = models.CharField (max_length=50, default='', blank=True)
    created_at = models.DateTimeField()
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.author.email

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Cart, Order


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "amount"]


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = "__all__"


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        

main/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, PostForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User, Group
from .models import Post, Cart, Order
import datetime

from django.db.models import Sum


# @login_required(login_url="/login")
def home(request):
    posts = Post.objects.all().order_by("title")
    if request.user:
        request.session["cart_count"] = Cart.objects.all().count()

    if request.method == "POST":
        
        post_id = request.POST.get("poist-d")
        user_id = request.POST.get("user-id")
        cart_id = request.POST.get("cart-id")

        if post_id:
            post = Post.objects.filter(id=post_id).first()
            if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
                post.delete()
        elif cart_id:
            cart = Cart.objects.create(author=request.user, post_id=cart_id)
            cart.save()
        elif user_id:
            user = User.objects.filter(id=user_id).first()
            if user and request.user.is_staff:
                try:
                    group = Group.objects.get(name='default')
                    group.user_set.remove(user)
                except:
                    pass
                try:
                    group = Group.objects.get(name='mod')
                    group.user_set.remove(user)
                except:
                    pass

    return render(request, 'main/home.html', {"posts": posts})



@login_required(login_url="/login")
def my_post(request):
    posts = Post.objects.filter(author=request.user).order_by("title")

    if request.method == "POST":
        post_id = request.POST.get("post-id")

        if post_id:
            post = Post.objects.filter(id=post_id).first()
            if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
                post.delete()

    return render(request, 'main/mypost.html', {"posts": posts})


@login_required(login_url="/login")
@permission_required("main.add_post", login_url="/login", raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("/mypost")
    else:
        form = PostForm()

    return render(request, 'main/create_post.html', {"form": form})


@login_required(login_url="/login")
@permission_required("main.change_post", login_url="/login", raise_exception=True)
def edit_post(request, id):
    print(id,"oooooooooo")
    post = Post.objects.filter(id=id)
    # for i in post:
    #     print(i,"iiiiiiiiiiii11")
    return render(request, 'main/edit_post.html', {"post": post})


@login_required(login_url="/login")
@permission_required("main.add_post", login_url="/login", raise_exception=True)
def update_post(request, id):
    post = Post.objects.get(id=id)  
    form = PostForm(request.POST, instance = post)  
    if form.is_valid():  
        form.save()  
        return redirect("/mypost")  
    return render(request, 'main/edit_post.html', {'post': post})  


@login_required(login_url="/login")
@permission_required("main.add_post", login_url="/login", raise_exception=True)
def my_cart(request):
    uid = request.user.id
    cart = Cart.objects.filter(author__id=uid)
    total = 0
    for ct in cart:
        total += ct.post.amount
    # total = Cart.objects.annotate(Sum(author__id=uid))
    # sum = Sale.objects.filter(type='Flour').aggregate(Sum('column'))['column__sum']
    # total = Cart.objects.all().aggregate(Min('price'))
    # Product.objects.all().aggregate(Min('price'))
    if request.user:
        request.session["cart_count"] = Cart.objects.all().count()

    if request.method == "POST":
        cart_post_id = request.POST.get("cart-post-id")
        place_order = request.POST.get("place-order")
        print(place_order,"------place_order-----------")
        if cart_post_id:
            post = Cart.objects.filter(author__id=uid, post__id=cart_post_id ).first()
            if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
                post.delete()
        
        elif place_order:
                for crt in cart:
                    order = Order.objects.create(
                        author = request.user,
                        post = crt.post,
                        address = "hyderabad",
                        phone = 9988776655,
                        created_at=datetime.datetime.now()
                        )
                    print(crt,"-crt---------")
                    order.save()
                cart = Cart.objects.filter(author__id=uid)
                for cart_item in cart:
                    cart_item.delete()

    return render(request, "main/my_cart.html", {'cart': cart, "total":total})


# @login_required(login_url="/login")
# @permission_required("main.change_post", login_url="/login", raise_exception=True)
# def place_order(request):
#     if request.user:
#         request.session["cart_count"] = Cart.objects.all().count()
#     uid = request.user.id
#     cart = Cart.objects.filter(author__id=uid)
#     print(cart)
#     try:
#         for crt in cart:
#             order = Order.objects.create(
#                 author = request.user,
#                 post = crt.post.id,
#                 address = "hyderabad",
#                 phone = 9988776655,
#                 )
#             print(crt,"-crt---------")
#             order.save()
#         cart = Cart.objects.filter(author__id=uid).delete()
#     except:
#         pass
#     return render(request, "main/place_order.html", {'cart': cart})


@login_required(login_url="/login")
@permission_required("main.change_post", login_url="/login", raise_exception=True)
def my_order(request):
    uid = request.user.id
    orders = Order.objects.filter(author__id=uid).order_by("-created_at")
    return render(request, "main/my_order.html", {'orders': orders})


def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = RegisterForm()

    return render(request, 'registration/sign_up.html', {"form": form})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}My Site{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/home">Home</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/mypost">My Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-post">Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/mycart/">Cart</a>
            </li>
            <span class="navbar-text">{{request.session.cart_count}} </span>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <li class="nav-item">
              <a class="nav-link" href="/myorder/">Orders</a>
            </li>        
            {% endif %}

          </ul>
        </div>
        <div>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <span class="navbar-text">Logged in as {{user.username}} | </span>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/sign-up">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- <div class="topnav">
      <a class="active" href="/home">Home</a>
      <a href="/create-post">New</a>
      <div class="topnav-right">
          {% if user.is_authenticated %}
          <span class="navbar-text">Logged in as {{user.username}} | </span>
          <a class="nav-link" href="logout">Logout </a>
          {% else %}
      
          <a class="nav-link" href="signup">Signup </a>
          <a class="nav-link" href="/login">Login </a>
          {% endif %}
      </div>
    </div> -->

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

main/templates/main/create_post.html
{% extends 'main/base.html' %} {% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} 
{% block content %}
<form method="post">
  {% csrf_token %}{{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

main/templates/main/edit_post.html
{% extends 'main/base.html' %} 
{% block title %} Edit a Post{% endblock %} 
{% load crispy_forms_tags %} 

{% block content %}


<form method="POST" class="post-form" action="/updatepost/{{post.id}}">  
    {% csrf_token %}  
      <div class="container" align="center">  
        <br>  
        <div class="form-group row">  
          <label class="col-sm-1 col-form-label"></label>  
          <div class="col-sm-4">  <h3>Update Details</h3>  </div>  
        </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Post Title :</label>  
        <div class="col-sm-4">  
        <input type="text" name="post_id" id="id_post_id" required maxlength="20" value="{{ course.title }}"/>  
        </div>  
        </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Course Description:</label>  
        <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="100" value="{{ course.description }}" />  
        </div>  
        </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Course Price:</label>  
        <div class="col-sm-4">  
        <input type="number" name="amount" id="id_amount" required maxlength="254" value="{{ course.amount }}" />  
        </div>  
        </div>  
        <br>
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        <button type="submit"><a href="/"> Cancel</a></button>  
        </div>  
        </div>  
      </div>  
    </form>  

<hr>
<br>
<form method="post">
  {% csrf_token %}{{form|crispy}}
  <button type="submit"  name='update_post' class="btn btn-success">Post</button>
</form>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %} 
  {% block title %}Home Page{% endblock %} 
{% block content %} 
{% for post in posts %}
<div class="card mt-2">
  <div class=" card-header text-muted btn-group" role="group" aria-label="Basic example" >
    <div>

      <strong>@{{ post.author.username }}</strong>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <div>
        {{ post.amount}}
    </div>
  </div>

  <div class="card-body d-flex flex-row justify-content-between">
    <div>
      <h5 class="card-title">{{post.title}}</h5>
      <p width='50ch', overflow='hidden'; >{{post.description}}</p>
    </div>
    <!-- <div>
      {% if user == post.author or perms.main.delete_post %}
      <form method="post">
        {% csrf_token %}
        <button
          type="submit"
          class="btn btn-danger"
          name="post-id"
          value="{{post.id}}"
        >
          Delete
        </button>
      </form>
      {% endif %}
      {% if user.is_staff %}
      <form method="post">
        {% csrf_token %}
        <button
          type="submit"
          class="btn btn-warning"
          name="user-id"
          value="{{post.author.id}}"
        >
          Ban User
        </button>
      </form>
      {% endif %}
    </div> -->
  </div>
  <div class="card-footer text-muted btn-group" role="group" aria-label="Basic example" >
    <div>
    <strong>{{post.created_at}}</strong>
    </div>

    {% if user != post.author and user.is_authenticated %}
    &nbsp;&nbsp;&nbsp;&nbsp;
    <div>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-warning" name="cart-id" value="{{post.id}}">
          Add To Cart
        </button>
      </form>
    </div>
    {% endif %}
  </div>

</div>
{% empty %}
  <p>No posts yet :( </p>
{% endfor %} 
{% endblock %}

main/templates/main/my_cart.html
{% extends 'main/base.html' %} 
{% block title %} My Cart {% endblock %} 
{% load crispy_forms_tags %} 

{% block content %}
<div class="container">
    <div class="border rounded p-4 m-4">
         <table class="table">
             <thead>
                 <tr>
                     <th>Sno.</th>
                     <th>Title</th>
                     <th>Description</th>
                     <th>Price</th>
                     <!-- <th>Total</th> -->
                     <th></th>
                 </tr>
             </thead>
             <tbody>
                 
                 {% for crt in cart %}
                 <tr>
                     <td>{{forloop.counter}}</td>
                     <td>{{crt.post.title}}</td>
                     <td>{{crt.post.description}}</td>
                     <!-- <td>{{crt.post.amount}}</td> -->
                     <td>{{crt.post.amount}}</td>
                     <td>
                        {% if user == post.author or perms.main.delete_post %}
                        <form method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger" name="cart-post-id" value="{{crt.post.id}}">
                            Remove
                          </button>
                        </form>
                        {% endif %}
                     </td>
                 </tr>
                 {% endfor %}
             </tbody>
              <tfoot>
                 <tr>
                     <th colspan="4"></th>
                     <th class="" colspan="">Total</th>
                     <th>{{total}}</th>
                 </tr>
             </tfoot>
         </table>
         <hr>
         <div class="m-3 p-3">
             <!-- <a href="/" name="place-order" value="True" class="btn btn-outline-success border rounded  col-lg-3 float-right">Purchase</a> -->
             {% if user and cart %}
             <form method="post">
               {% csrf_token %}
               <button type="submit" class="btn btn-outline-success border rounded  col-lg-3 float-right"  name="place-order" value="True" >
                Purchase
               </button>
             </form>
             {% endif %}
            </div>
    </div>
 </div>
 
 
 <!-- modal -->
 
   <!-- Modal -->
   <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title" id="exampleModalLabel">
               Check Out Form
           </h5>
           <hr>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
         <div class="modal-body">
           <div class="m-2 p-3">
             <form action="/check-out" method="POST">
                 {% csrf_token %}
                 <div class="form-group">
                   <label for="">Address</label>
                   <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                   
                 </div>
                 <div class="form-group">
                     <label for="">Phone</label>
                     <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                   </div>
 
                   <input type="submit" class="btn float-right btn-outline-success col-lg-6" value="Check out">
             </form>
           </div>
         </div>
         
       </div>
     </div>
   </div>
 
 
 
 {% endblock %}

main/templates/main/my_order.html
{% extends 'main/base.html' %} 
{% block title %} My Cart {% endblock %} 
{% load crispy_forms_tags %} 

{% block content %}
<div class="container">
    <div class="border rounded p-4 m-4">
         <table class="table">
             <thead>
                 <tr>
                     <th>Sno.</th>
                     <th>Title</th>
                     <!-- <th>Address</th>
                     <th>Phone. No.</th> -->
                     <th>Price</th>
                     <th>Date</th>
                     <th>Status</th>
                 </tr>
             </thead>
             <tbody>
                 
                 {% for order in orders %}
                 <tr>
                     <td>{{forloop.counter}}</td>
                     <td>{{order.post.title}}</td>
                     <!-- <td>{{order.address}}</td>
                     <td>{{order.phone}}</td> -->
                     <td>{{order.post.amount}}</td>
                     <td>{{order.created_at}}</td>
                     <td>Pending</td>
                 </tr>
                 {% empty %}
                 <P> No orders yet :( continue shoping <a href="/"> here</a> !</P>
                 {% endfor %}
             </tbody>
         </table>
    </div>
 </div>
{% endblock %}

main/templates/main/my_post.html
{% extends 'main/base.html' %} 
  {% block title %}My Post{% endblock %} 
{% block content %} 

{% for post in posts %}
<div class="card mt-2">
    <div class=" card-header text-muted btn-group" role="group" aria-label="Basic example" >
        <div>
            <strong>{{post.title}}</strong>
        </div>
            &nbsp;&nbsp;&nbsp;&nbsp;
        <div>
            {{ post.amount}}
        </div>
    </div>
    <div class="card-body d-flex flex-row justify-content-between">
        <p>{{post.description}}</p>
    </div>
    <div class="card-footer text-muted btn-group" role="group" aria-label="Basic example">
        <div>
            <p>{{post.created_at}} &nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
        <div>
            <button type="button" class="btn btn-success ml-2"><a href="editpost/{{post.id}}">Edit</a></button>
        </div> 
            &nbsp;&nbsp;&nbsp;&nbsp;
        <div>
            {% if user == post.author or perms.main.delete_post %}
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" name="post-id" value="{{post.id}}"> Delete </button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% empty %}
  <p>No posts yet :( </p>
{% endfor %} 
{% endblock %}

main/templates/main/mypost.html
{% extends 'main/base.html' %} 
  {% block title %}My Post{% endblock %} 
{% block content %} 
{% for post in posts %}
<div class="card mt-2">
    <div class=" card-header text-muted btn-group" role="group" aria-label="Basic example" >
        <div>

        <strong>{{post.title}}</strong>
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <div>
            {{ post.amount}}
        </div>
    </div>

    <div class="card-body d-flex flex-row justify-content-between">
        <p>{{post.description}}</p>
    </div>
    <div class="card-footer text-muted btn-group" role="group" aria-label="Basic example">
        <div>
            <p>{{post.created_at}} &nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
        <div>
            <button type="button" class="btn btn-secondary ml-2"><a href="editpost/{{post.id}}/">Edit</a></button>
        </div> 
        &nbsp;&nbsp;&nbsp;&nbsp;
        <div>
            {% if user == post.author or perms.main.delete_post %}
            <form method="post">
            {% csrf_token %}
            <button
                type="submit"
                class="btn btn-danger"
                name="post-id"
                value="{{post.id}}"
            >
                Delete
            </button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% empty %}
  <p>No posts yet :( </p>
{% endfor %} 
{% endblock %}